### PR TITLE
Clean up `Ctor`s

### PR DESCRIPTION
**Pull request by taha-ghadirian**

### CODE REVIEW

**Comment by NdubuisiJr** [comment]
Hi @taha-ghadirian 

I think it would be nice if we made the `_fadeTimout` field a Dependency (Bindable) property just like the `NotificationMessage` and `Position` properties. With that, we wouldn't need to overload the constructor and it will make the whole stuff more consistent. Again the `_fadeTimout` is not properly spelled :)

**Comment by NdubuisiJr** [comment]
A lot of properties are bound to come in, to further make the `Toasts` flexible, that's why we created the `ToastBase.Properties.cs` partial class. That should contain all properties that customize the behavior of the notifications. Please do well to use it. 

Thanks :)

**Review by bloggrammer — CHANGES_REQUESTED** [review]
@taha-ghadirian can we make the fadeTimeOut a dependency property rather than a field? Also, look at the suggestion made by @NdubuisiJr regarding creating properties for the `ToastBase` in the `ToastBase.Properties.cs` file.

Thanks!

**Comment by taha-ghadirian** [comment]
@Blogrammer Need 3-4 days for applying this change request ;( 
Can you assign it to others if you cant wait?

**Pull request closed without merging**
